# Copyright (c) 2025 Oleksiy Oleksandrovych Sayankin. All Rights Reserved.
# Refer to the LICENSE file in the root directory for full license details.

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/server.log
    mode: a
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

loggers:
  "":
    level: INFO
    handlers: [file_handler, console]
    propagate: no

root:
  level: INFO
  handlers: [file_handler, console]
