{
 "title": "Main Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "gRPC Server",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"gRPC Server\"}"
    }
   ]
  },
  {
   "title": "Web Server",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"web-server\"}"
    }
   ]
  },
  {
   "title": "Result Consumer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"Result Consumer\"}"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service=\"Executor\"}"
    }
   ]
  }
 ]
}