# Copyright (c) 2025 Oleksiy Oleksandrovych Sayankin. All Rights Reserved.
# Refer to the LICENSE file in the root directory for full license details.

[pytest]
filterwarnings =
    ignore:The @wait_container_is_ready decorator is deprecated.*:DeprecationWarning:testcontainers\.rabbitmq.*
