# Copyright (c) 2025 Oleksiy Oleksandrovych Sayankin. All Rights Reserved.
# Refer to the LICENSE file in the root directory for full license details.

server:
  host: "0.0.0.0"
  port: 8000
  log_level: "info"
  reload: "true"
